language: bash

before_install:
  - bash travis/packer-install.sh

script:
  - bash travis/packer-build.sh

env:
  global:
    - AWS_SOURCE_AMI='ami-a10897d6'

notifications:
  slack:
    rooms:
      - { secure: moi2GzezCUtY7XJFvyzhzPjLyo1+Eb95RlrNpTD2yvNa+knMIVHlVSfttJBierRq2lW8dkeicWix0jNgGOwjC6qmiBFuzovU/Sm0/uguKt+rWiOtKtYWXyW4Wx9BQcYXZQe5C28gYrSsYkDZGn13xScq2MTblSgn99uwwlvPJ+8h22kS3lUUFuH5dnEp0lVvY0eo3cnbr9IJFNlz6rIXN6XqQu7SEsJhJg4TZcRhz3OtVmcd0DIFuzJen1RJWMJzIfmJL31WTsXzygh/PdtaMX9PLGX/rwrXp+6TgMbGmcyESgBUPt25ILVjwaFIyenwvLA+5FZDvtO49ejqSOojVO/aJi+SO+bmuIim/zhCes5R9RlzaicaMN0KphPgsOvykgwya1eJKRIsYXzrKZiRG0USo1XiPa7e3DF0xIA6Uy2edbk7B7p/3Nj8rhEftIu9A4jGc3cm8Hb4pfS8Juaq0bHTvFGL5HCqqb69Bnb2t3TfR5ErDef/p7RZkAgPADuwKeKf7/zbx3R9TRUk8fqUikBA6ghKPvluVYLjfiqasR1OvfMGvcxSAmaMB7EUNI1DNoGC2wmAanJ/uY+aJMAInwgGKNjeV+R1yV+oPpRXLwooAcM2FNnITtrwv/2RH5t9d8j9gCVfT6HJRVP2dxCc/PaIMu380Qiwp5hcWwxvo04= }
